// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrxqoPphUWpqahzbmM3jMfzDihXDdqEc',
    appId: '1:34668335333:web:041b15d6d6f62e90d6c40c',
    messagingSenderId: '34668335333',
    projectId: 'knucklebones-f84d2',
    authDomain: 'knucklebones-f84d2.firebaseapp.com',
    storageBucket: 'knucklebones-f84d2.appspot.com',
    measurementId: 'G-WYN2G6E6E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKvnj-JxRqMEro3YWadc65bXQyLcdVIEo',
    appId: '1:34668335333:android:d0dbf5157372458dd6c40c',
    messagingSenderId: '34668335333',
    projectId: 'knucklebones-f84d2',
    storageBucket: 'knucklebones-f84d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGxvHoYR1wnxouT9_XU2B3y9Byn8SpOlc',
    appId: '1:34668335333:ios:5268f222232161a7d6c40c',
    messagingSenderId: '34668335333',
    projectId: 'knucklebones-f84d2',
    storageBucket: 'knucklebones-f84d2.appspot.com',
    iosClientId: '34668335333-bdqkpffnephkgb4i0ltutmb5pntgd0f6.apps.googleusercontent.com',
    iosBundleId: 'com.hawkins.knucklebones',
  );
}
